sharding:
  jdbc:
    datasource:
      ds0:
        password: wangyang
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.24.0.221:3306/shard_1
        username: root
      ds1:
        password: wangyang
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.24.0.221:3306/shard_2
        username: root
      names: ds0,ds1
    config:
      sharding:
        tables:
          employee:
            actual-data-nodes: ds$->{0..1}.employee_$->{0..1}
            database-strategy:
              inline:
                  sharding-column: id
                  algorithm-expression: ds$->{id % 2}
            table-strategy:
              standard:
                  sharding-column: code
                  precise-algorithm-class-name: com.tryndamere.zhibo8.trynpersistent.custom.route.CommonDataBaseStrategy

#分表算法节点
murmur:
  node: 2

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
  redis:
    host: 47.105.146.39
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 5s


  datasource:
    schema: classpath:schema-mysql.sql
    schema-username: root
    schema-password: wangyang
    initialization-mode: never
    url: jdbc:mysql://118.24.0.221:3306/shard_1
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 47.105.146.39:9300
      repositories:
        enabled: true

mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.tryndamere.zhibo8.trynmodel.pojo
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
