server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
logging:
  level:
    com:
      netflix:
        discovery: OFF
        eureka: OFF
spring:
  application:
    name: tryn-registry