server:
  port: 8082
  tomcat:
    max-threads: 1000
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  redis:
    password:
    cluster:
      nodes: 47.103.3.192:7000,47.103.3.192:7001,47.103.3.192:7002,47.103.3.192:7003,47.103.3.192:7004,47.103.3.192:7005
      max-redirects: 3
    lettuce:
      pool:
        max-idle: 10
        max-active: 8
        min-idle: 3
        max-wait: 2000ms
