server:
  port: 8081
  tomcat:
    max-threads: 1000
spring:
  profiles:
    active: common,business,persistent
  application:
    name: tryn-api
  sleuth:
    sampler:
      probability: 1.0
    enabled: true
  zipkin:
    base-url: ${ZIPKIN_SERVICE_URL:http://localhost:9411/}
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true