server:
  port: 8080
  tomcat:
    max-threads: 4000
zuul:
  host:
    max-total-connections: 4000
    max-per-route-connections: 400
  routes:
    users:
      path: /bd/**
      serviceId: tryn-api
      strip-prefix: false
  ribbon-isolation-strategy: thread
  ribbon:
    eager-load:
      enabled: true
    threadPool:
      useSeparateThreadPools: true
      threadPoolKeyPrefix: api-gateway
  #关闭重试
  retryable: false
  #/oauth/token需要请求头处理
  sensitive-headers:
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Allow-Methods
  add-host-header: true

spring:
  # sentinel动态配置规则
  cloud:
    sentinel:
      datasource:
        # 限流
        ds1:
          nacos:
            server-addr: ${tryn.nacos.server-addr}
            dataId: sentinel-flow
            groupId: DEFAULT_GROUP
            rule-type: flow
        # 熔断
        ds2:
          nacos:
            server-addr: ${tryn.nacos.server-addr}
            dataId: sentinel-degrade
            groupId: DEFAULT_GROUP
            rule-type: degrade
        # 系统负载保护
        ds4:
          nacos:
            server-addr: ${tryn.nacos.server-addr}
            dataId: sentinel-system
            groupId: DEFAULT_GROUP
            rule-type: system


hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 2000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000