server:
  port: 8080
spring:
  rabbitmq:
    host: 47.103.3.192
    port: 5672
    username: admin
    password: admin
  datasource:
    druid:
      max-active: 200
      initial-size: 5
      min-idle: 5
      url: jdbc:mysql://47.103.3.192/zhibo8?useUnicode=true&generateSimpleParameterMetadata=true&useSSL=false
      username: root
      password: 123456
      test-on-borrow: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 18000000
  redis:
    password:
    cluster:
      nodes: 47.103.3.192:7000,47.103.3.192:7001,47.103.3.192:7002,47.103.3.192:7003,47.103.3.192:7004,47.103.3.192:7005
      max-redirects: 3
    lettuce:
      pool:
        max-idle: 100
        max-active: 200
        min-idle: 10
        max-wait: 2000ms



mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.tryndamere.zhibo8.harvest.entity
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: id_worker

rabbitmq:
  consumer:
    concurrentConsumers: 15
    maxConcurrentConsumers: 20
    executor:
      size: 100

xxl:
  job:
    executor:
      logpath: logs
      appname: zhibo8
      port: 9999
      logretentiondays: 3
      ip:
    admin:
      addresses: http://localhost:8081/
    accessToken: